### ISSUE TITLE
Update Tournament, Participant and Match models with missing fields

### ISSUE THREAD

**Issue by gpluscb** [stefangeyer/challonge-java#14]
I decided to look at the raw output of the api for the routes to get a tournament, get a participant, get a match and get an attachment and it appears that there are some fields in the raw json output that are not present in their respective java models. Some of them make sense, but for some I have no idea what they mean or even what type they are.

### Tournament
- Boolean ranked
- Boolean predict_the_losers_bracket
- ?(was null) spam
- ?(was null) ham
- Integer rr_iterations
- ?(probably Long, was null) tournament_registration_id
- ?(probably Boolean, was null) donation_contest_enabled
- ?(maybe Float, was null) mandatory_donation
- Object non_elimination_tournament_data, fields:
    - ?(Integer would make sense, but was empty String) participants_per_match
- ?(probably Boolean, was null) auto_assign_stations
- ?(probably Boolean, was null) only_start_matches_with_stations
- Float registration_fee
- String(could probably be an enum, but would require more research) registration_type

On another note, tieBreaks could use an enum, all options I could get via tournament settings are:
- "match wins"
- "game wins"
- "game win percentage"
- "points scored"
- "points difference"
- "match wins vs tied"
- "median buchholz"

### Participant
- ?(probably Long, was null) ranked_member_id
- String display_name
- Boolean check_in_open
- List<?(probably Long, was empty)> group_player_ids
- Boolean has_irrelevant_seed

### Match
- Boolean optional
- ?(probably Long, was null) rushb_id (no typo)
- OffsetDateTime completed_at
- Boolean forfeited

### Attachment
none found

All of these are typed out by hand, so there might be some typos but I hope there are none. If there are some, I apologize. The raw data I got from my api calls is below.

[attachment.json.txt](https://github.com/stefangeyer/challonge-java/files/3642120/attachment.json.txt)
[match.json.txt](https://github.com/stefangeyer/challonge-java/files/3642121/match.json.txt)
[participant.json.txt](https://github.com/stefangeyer/challonge-java/files/3642122/participant.json.txt)
[tournament.json.txt](https://github.com/stefangeyer/challonge-java/files/3642123/tournament.json.txt)

**Comment by gpluscb** [comment]
Did a bit more research:
- participants_per_match is a String, however it only contains Integers or nothing.
- auto_assign_stations is in fact a Boolean
- only_start_matches_with_stations is in fact a Boolean
- registration_type *might* be a enum with either "free" or "paid" as options
For the ham, spam and rushb_id things, I have no clue. Anything donation related I will not be able to test.

**Comment by stefangeyer** [comment]
I've added all the params of which we know the type for sure. I won't add any of the params that only return null values. I am pretty busy at the moment and I therefore cannot really do a lot of research myself, but as long as we cannot be sure about the type and nullability of a property it would be just too error prone to add them. Sadly the api docs are not being updated which makes the process of keeping the library up to date a lot harder. 

Thanks for all the work you put into this. All changes will be available in the upcoming release. If you want to investigate or test any further for now, feel free to use the latest snapshot from the [snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/at/stefangeyer/challonge/).

**Comment by gpluscb** [comment]
Honestly, thank you for developing and maintaining this repo.

Only adding the safe fields does certainly make a lot of sense. I'll let the choice to close this issue to you, but I don't think I will look into these weird fields any more either, at least until the API changes in a significant way like for example supporting free for all tournaments. Personally, I'd close it but I'll leave it to you.
*(Also just noticed while writing this, found in the raw API response but didn't test in this wrapper: the tournament_type field in the tournament json now allows for a "free for all" type, should break in a similar way to #13 with the tournament "f7jclqup")*

By the way, Challonge support promised me that they "have plans to update their API", but I wouldn't get too excited about it.
On another note, on their [API documentation site](https://api.challonge.com/v1), Challonge supports third party libraries and I think yours would fit there, if you want to annoy Challonge about that.

In case I find another issue that would be within my capabilities to fix, I could just try to fix it myself and open a pr, if you would appreciate that.

**Comment by stefangeyer** [comment]
_Added the free for all tournament type._

Yeah, the API overhaul has been promised for years now. Might not be happening anytime soon. Also feel free to contribute to this project if you want to 👍.
