### ISSUE TITLE
Attachment asset uploads do not work

### ISSUE THREAD

**Issue by EXSolo** [stefangeyer/challonge-java#3]
Neither encoding a file with Base64 nor sending a multipart/form-data request were accepted by the API. Can't figure out how to fix this at the moment.

**Comment by stefangeyer** [comment]
Challonge have fixed some bugs due to my report. I'll attempt to implement this again

**Comment by stefangeyer** [comment]
File uploads are now possible via multipart request. Issue fixed in the latest [commit](https://github.com/stefangeyer/challonge-java/commit/21090040819cef0fd6a09b4a32db66d4fee79603)
