### ISSUE TITLE
Error injecting constructor, java.lang.NoClassDefFoundError: com/exsoloscript/challonge/library/javax/net/ssl/HostnameVerifier

### ISSUE THREAD

**Issue by ScalaWilliam** [stefangeyer/challonge-java#5]
Hi, I was keen to try out this library via Scala (SBT project, so my test project isn't missing dependencies) and it doesn't work.

Same thing happens in this reproducible case with Nashorn:

```
$ wget http://central.maven.org/maven2/com/exsoloscript/challonge/challonge-java/1.0/challonge-java-1.0.jar
...
$ jjs -cp challonge-java-1.0.jar
jjs> var Challonge = Java.type("com.exsoloscript.challonge.Challonge")
jjs> Challonge.getFor("A", "B")
com.exsoloscript.challonge.library.google.inject.ProvisionException: Unable to provision, see the following errors:
...
```

I tried this on an OS X machine and a CentOS 7 machine.

The full stack trace is TLDR so pasted here: https://gist.github.com/ScalaWilliam/5b15f653736881b2aad53993b0a55d0b

PS I notice this <a href="https://mvnrepository.com/artifact/com.exsoloscript.challonge/challonge-java/1.0">JAR depends on JUnit</a> as well. Not sure that should be in compile time dependency. It imports hamcrest library, I wasn't sure where that was coming from.

**Comment by stefangeyer** [comment]
This is odd. It looks like the shaded dependencies are missing. I also thought I had JUnit excluded from the shade process. Weird. I'll look into it, but it might take a while, since I am quite busy at the moment.

**Comment by stefangeyer** [comment]
The bug you encountered should be fixed. I also removed junit and hamcrest from the shading process.
