### ISSUE TITLE
More than one file was found with OS independent path 'lombok/eclipse/handlers/HandleLog$LoggingFramework.SCL.lombok'

### ISSUE THREAD

**Issue by byvlstr** [stefangeyer/challonge-java#8]
Hi,

I am on Android with Gradle Plugin 3.0.1 and Gradle 4.1 and I cannot run the app due to the following error. It seems to come from the library.

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDevDebug'.
> More than one file was found with OS independent path 'lombok/eclipse/handlers/HandleLog$LoggingFramework.SCL.lombok'

Thanks

Valentin

**Comment by stefangeyer** [comment]
I will look into this

**Comment by stefangeyer** [comment]
@byvlstr There is a good chance that this has already been fixed in a0d09be33c7657a4a5e4176e656867d934693b27 where I removed lombok from the shading process. I will release a new version on maven central soon. Please check if this error still occurs with the new version.

**Comment by byvlstr** [comment]
Ok thanks :) ! Well I used the latest version. I saw that you already fixed something with Lombok but it still didn't work...

FYI
Target and compile Android SDK is 26
Use of gradle wrapper 4.1

Usage in the gradle file:
    annotationProcessor group: 'com.exsoloscript.challonge', name: 'challonge-java', version: '1.0.2'
    compile group: 'com.exsoloscript.challonge', name: 'challonge-java', version: '1.0.2'

**Comment by stefangeyer** [comment]
As I said, a0d09be33c7657a4a5e4176e656867d934693b27 is not included in release `1.0.2`. I will release 1.0.3 soon, where the bug you encountered is probably fixed. Until then this issue will be on hold.

**Comment by byvlstr** [comment]
Great! Thanks :)

PS: I tried last week to add participants to a tournament I created (used both URL and id) but I got an error message saying I don't have the rights to edit the tournament. Could you please confirm this is still working? (Maybe they changed something in the API calls)

**Comment by stefangeyer** [comment]
Version `1.0.3` is now available on maven central. Please check if your issue was fixed. Also, adding participants should now work again.

**Comment by byvlstr** [comment]
Hi,
I tried again but the Android build now shows another error (see below). No worries, maybe your library wasn't targeting Android.

Also: I tried with my UnitTest and adding Participants still didn't work.

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\Valentin\.gradle\caches\modules-2\files-2.1\com.exsoloscript.challonge\challonge-java\1.0.3\5c6aa7e95ae66a18f73e68099a11ef911ecb8505\challonge-java-1.0.3.jar

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/exsoloscript/challonge/handler/call/RetrofitChallongeApiCall.class

Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

**Comment by stefangeyer** [comment]
This library uses guice and therefore also uses guava. As you probably know it is not recommended to use either of these libraries with android. I am planning to rework my library so it can be used with mobile applications as well. Until then I would advise against using it with android. Since the lombok issue is resolved, I am closing this issue.
